### ISSUE TITLE
Make releases

### ISSUE THREAD

**Issue by ckiee** [michaelrsweet/hp-printer-app#13]
**Is your feature request related to a problem? Please describe.**
I'm trying to package `hp-printer-app` for [nixpkgs/NixOS](https://github.com/nixos/nixpkgs) and it looks like I'll have to pin it to a specific commit since you haven't made any releases/tags. It'd be nice if I wouldn't have to.

**Describe the solution you'd like**
Releases with tags.

**Describe alternatives you've considered**
Continuing as I already am and just pinning to a commit.

**Additional context**
<PR hasn't been made yet, maybe I'll throw it in here later>

**Comment by michaelrsweet** [comment]
@ckiee Originally this repository was just going to be sample code - I honestly didn't think anyone would want to pick this up as an actual solution. But since people are I *will* be doing releases going forward (once I get things working at the level *I* expect for a production solution, at least... :)
